services:
  nginx:
    build: ./nginx
    ports:
      - '1337:80'
    depends_on:
      - web
    volumes:
      - static-data:/var/www/uplearn/static

  postgres:
    image: "postgres:alpine"
    shm_size: 128mb
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}

  web:
    build: ./backend
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend/ :/user/src/backend/
    expose:
      - 8000
    depends_on:
      - daphne
      - redis
      - postgres
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DEBUG=${DEBUG}
      - DJANGO_LOGLEVEL=${DJANGO_LOGLEVEL}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - DATABASE_ENGINE=${DATABASE_ENGINE}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}

  daphne:
    build: ./backend
    command: daphne --bind 0.0.0.0 -p 8005 backend.asgi:application
    volumes:
      - ./backend/ :/user/src/backend/
      - static-data:/var/www/uplearn/static
    ports:
      - '8005:8005'
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis_cache:/data

volumes:
  redis_cache:
  static-data:
  postgres_data:




