# Generated by Django 5.1.4 on 2025-03-02 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("chat", "0002_initial")]

    operations = [migrations.RemoveField(model_name="conversation", name="modified")]
