# Generated by Django 5.1.4 on 2025-01-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcontent',
            name='deadline',
            field=models.DateTimeField(null=True),
        ),
    ]
