# Generated by Django 5.1.4 on 2025-01-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0002_itemcontent_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcontent',
            name='deadline',
        ),
        migrations.AddField(
            model_name='studyitem',
            name='deadline',
            field=models.DateTimeField(null=True),
        ),
    ]
