# Generated by Django 5.1.4 on 2025-01-14 12:33

import elearning.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0002_alter_courseprogress_user_alter_topic_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcontent',
            name='file',
            field=models.FileField(null=True, upload_to=elearning.models.course_topic_directory_path),
        ),
        migrations.AlterField(
            model_name='itemcontent',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='itemcontent',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='itemcontent',
            name='video',
            field=models.FilePathField(null=True, path='media/video'),
        ),
    ]
