# Generated by Django 5.1.4 on 2025-01-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0003_remove_itemcontent_deadline_studyitem_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenrollment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default='2025-01-01 00:00'),
            preserve_default=False,
        ),
    ]
