# Generated by Django 5.1.4 on 2025-01-14 12:35

import elearning.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0003_alter_itemcontent_file_alter_itemcontent_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcontent',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=elearning.models.course_topic_directory_path),
        ),
        migrations.AlterField(
            model_name='itemcontent',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='itemcontent',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemcontent',
            name='video',
            field=models.FilePathField(blank=True, null=True, path='media/video'),
        ),
    ]
