# Generated by Django 5.1.4 on 2025-01-14 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0004_alter_itemcontent_file_alter_itemcontent_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='elearning.course'),
        ),
    ]
