# Generated by Django 5.1.4 on 2025-01-16 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0004_courseenrollment_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseprogress',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_done_status', to='elearning.studyitem'),
        ),
    ]
