# Generated by Django 5.1.4 on 2025-01-14 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0005_alter_topic_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyitem',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_lessons', to='elearning.topic'),
        ),
    ]
