# Generated by Django 5.1.4 on 2025-01-17 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0005_alter_courseprogress_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyitem',
            name='course',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='elearning.course'),
            preserve_default=False,
        ),
    ]
