# Generated by Django 5.1.4 on 2025-01-14 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0006_alter_studyitem_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='elearning.course'),
        ),
    ]
