# Generated by Django 5.1.4 on 2025-01-17 13:51

import elearning.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0006_studyitem_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='desc',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.DurationField(validators=[elearning.validators.validate_course_duration]),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('teacher', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('course', 'title')},
        ),
    ]
