# Generated by Django 5.1.4 on 2025-01-17 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0007_rename_desc_topic_description_alter_course_duration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='desc',
            new_name='description',
        ),
    ]
