# Generated by Django 5.1.4 on 2025-01-17 16:32

import elearning.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0008_rename_desc_course_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='itemcontent',
            name='kind',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'image'), ('file', 'File'), ('video', 'Video')], max_length=24),
        ),
        migrations.AlterField(
            model_name='topic',
            name='n_hours',
            field=models.DurationField(validators=[elearning.validators.validate_topic_duration]),
        ),
        migrations.AlterUniqueTogether(
            name='courseenrollment',
            unique_together={('user', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='courseprogress',
            unique_together={('enrolled_student', 'item')},
        ),
        migrations.AlterUniqueTogether(
            name='feedback',
            unique_together={('user', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='studyitem',
            unique_together={('topic', 'title')},
        ),
    ]
