# Generated by Django 5.1.4 on 2025-01-14 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0008_course_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcontent',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='elearning.studyitem'),
        ),
    ]
