# Generated by Django 5.1.4 on 2025-01-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0009_alter_itemcontent_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyitem',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
