# Generated by Django 5.1.4 on 2025-01-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0010_studyitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcontent',
            name='kind',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'image'), ('file', 'File'), ('Video', 'Video')], max_length=24),
        ),
        migrations.DeleteModel(
            name='ContentType',
        ),
    ]
