# Generated by Django 5.1.4 on 2025-01-14 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0011_alter_itemcontent_kind_delete_contenttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcontent',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='elearning.studyitem'),
        ),
    ]
