# Generated by Django 5.1.4 on 2025-01-14 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0012_alter_itemcontent_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcontent',
            name='order',
        ),
    ]
