# Generated by Django 5.1.4 on 2025-01-14 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0013_remove_itemcontent_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcontent',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemcontent',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='elearning.studyitem'),
        ),
    ]
