# Generated by Django 5.1.4 on 2025-01-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0014_itemcontent_order_alter_itemcontent_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
