# Generated by Django 5.1.4 on 2025-01-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0015_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
