# Generated by Django 5.1.4 on 2025-03-09 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("elearning", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="feedback", name="text", field=models.TextField()
        )
    ]
