# Generated by Django 5.1.4 on 2025-03-01 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("elearning", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="enrollment",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedback",
                to="elearning.courseenrollment",
            ),
        )
    ]
