# Generated by Django 5.1.4 on 2025-03-01 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("elearning", "0002_alter_feedback_enrollment")]

    operations = [
        migrations.AddField(
            model_name="courseenrollment",
            name="done_lessons",
            field=models.ManyToManyField(
                related_name="students", to="elearning.lesson"
            ),
        ),
        migrations.DeleteModel(name="CourseProgress"),
    ]
