# Generated by Django 5.1.4 on 2025-03-09 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("elearning", "0002_alter_student_user_alter_teacher_user")]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        )
    ]
