# Generated by Django 5.1.4 on 2025-03-08 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0003_courseenrollment_done_lessons_delete_courseprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyholder',
            name='token',
            field=models.UUIDField(),
        ),
    ]
